apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-pv"  # Pour un environnement de développement local
    # Note : Pour un environnement de production, utiliser un stockage réseau (NFS, Ceph, etc.)

