apiVersion: v1
kind: Pod
metadata:
  name: web-red
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: red-ctnr-web
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
