apiVersion: v1
kind: Pod
metadata:
  name: web-blue
  namespace: production
  labels:
    app: web
spec:
  containers:
  - name: blue-ctnr-web
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: blue
